# Compiler and flags
CC = gcc

# Source files
SRCS = client.c naming_server_connection.c storage_server_connection.c

# Output executable
TARGET = client

# Build rule
all:
	$(CC) $(SRCS) -o $(TARGET)

# Clean up rule
clean:
	rm -f $(TARGET)
